# Defines the production Docker services for Digi2
services:

  # PostgreSQL database container
  db:
    image: postgres:16
    container_name: digi2-db
    restart: unless-stopped

    # Environment variables used by PostgreSQL on first startup
    environment:
      POSTGRES_DB: digi2
      POSTGRES_USER: digi2_user
      POSTGRES_PASSWORD: digi2_password

    # Exposes PostgreSQL to your computer for debugging
    expose:
      - "5432"

    # Keeps database data even if the container stops
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U digi2_user"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - digi2-network

  backend:
    image: 385018113052.dkr.ecr.us-east-1.amazonaws.com/digi2-backend:${BACKEND_IMAGE_TAG}
    container_name: digi2-backend
    restart: unless-stopped
    mem_limit: 1g

    # Run Django securely using Gunicorn WSGI server instead of development server
    command: gunicorn digi2_api.wsgi:application --bind 0.0.0.0:8000 --workers 1

    # Backend is reachable by Nginx inside Docker only.
    expose:
      - "8000"

    # Loads variables from .env
    env_file:
      - .env
      
    volumes:
      - media_volume:/app/media

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Backend starts after database container
    depends_on:
      db:
        condition: service_healthy
    networks:
      - digi2-network

  # Next.js frontend container
  frontend:
    image: 385018113052.dkr.ecr.us-east-1.amazonaws.com/digi2-frontend:${FRONTEND_IMAGE_TAG}
    container_name: digi2-frontend
    restart: unless-stopped
    mem_limit: 1g
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    expose:
      - "3000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - digi2-network

  nginx:
     image: nginx:latest
     container_name: digi2-nginx
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"

     volumes:
       - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       - ./certbot/conf:/etc/letsencrypt:ro
       - ./certbot/www:/var/www/certbot:ro
       - media_volume:/app/media

     healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost/"]
       interval: 30s
       timeout: 10s
       retries: 3
       start_period: 40s
     depends_on:
       frontend:
         condition: service_healthy
       backend:
         condition: service_healthy
     networks:
       - digi2-network

  certbot:
     image: certbot/certbot:latest
     container_name: digi2-certbot
     restart: unless-stopped
     volumes:
       - ./certbot/conf:/etc/letsencrypt
       - ./certbot/www:/var/www/certbot
     entrypoint: >
       /bin/sh -c "trap exit TERM;
       while :; do
       certbot renew --webroot -w /var/www/certbot --quiet;
       sleep 12h & wait $${!};
       done;"
     networks:
       - digi2-network

  prometheus:
    image: prom/prometheus:latest
    container_name: digi2-prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - digi2-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: digi2-grafana
    restart: unless-stopped

    environment:
      - GF_SERVER_ROOT_URL=https://digibab.com/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=digi2site@gmail.com
      - GF_SMTP_PASSWORD=fgmehzzeynnpwycp 
      - GF_SMTP_FROM_ADDRESS=digi2site@gmail.com
      - GF_SMTP_FROM_NAME=DIGI2 Alerts
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
      
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - digi2-network
    expose:
      - "3000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: digi2-node-exporter
    restart: unless-stopped
    networks:
      - digi2-network
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: digi2-cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - digi2-network
    ports:
      - "8080:8080"

  loki:
    image: grafana/loki:latest
    container_name: digi2-loki
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    networks:
      - digi2-network
    expose:
      - "3100"

  promtail:
    image: grafana/promtail:latest
    container_name: digi2-promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - digi2-network
    depends_on:
      - loki

# Named Docker volume for database persistence
volumes:
  postgres_data:
  media_volume:
  prometheus_data:
  grafana_data:
  loki_data:

networks:
  digi2-network:
    name: digi2-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-digi2
