server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://digi2-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-containers
          host: digi2-ec2
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: falco
    static_configs:
      - targets:
          - localhost
        labels:
          job: falco
          host: digi2
          __path__: /var/log/falco-events.log