# Generated by Django 5.1.4 on 2026-05-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessprofile_delete_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verification status.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_area',
            field=models.CharField(blank=True, help_text='Areas covered by this business, e.g. Toronto, Brampton, GTA.', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Business address or operating address.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(help_text='Public name of the business.', max_length=255),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City where the business operates.', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this business profile was created.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Short explanation of what the business does.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional business logo.', null=True, upload_to='business_logos/'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='owner',
            field=models.OneToOneField(help_text='The user who owns this business profile.', on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Business contact phone number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date this business profile was last updated.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Optional business website.'),
        ),
    ]
