# Generated by Django 5.1.4 on 2026-05-11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists.",
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator(),
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="last name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("handyman", "Handyman"),
                            ("business_owner", "Business Owner"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        help_text="Defines what this user can access inside the platform.",
                        max_length=30,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional phone number for contact or business use.",
                        max_length=30,
                    ),
                ),
                (
                    "is_profile_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Used to know if the user has completed onboarding.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time this user account was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time this user account was last updated.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF to_regclass('public.auth_user') IS NOT NULL THEN
                        INSERT INTO accounts_user (
                            id,
                            password,
                            last_login,
                            is_superuser,
                            username,
                            first_name,
                            last_name,
                            email,
                            is_staff,
                            is_active,
                            date_joined,
                            role,
                            phone,
                            is_profile_completed,
                            created_at,
                            updated_at
                        )
                        SELECT
                            id,
                            password,
                            last_login,
                            is_superuser,
                            username,
                            first_name,
                            last_name,
                            email,
                            is_staff,
                            is_active,
                            date_joined,
                            'customer',
                            '',
                            false,
                            date_joined,
                            date_joined
                        FROM auth_user
                        ON CONFLICT (id) DO NOTHING;
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF to_regclass('public.auth_user_groups') IS NOT NULL THEN
                        INSERT INTO accounts_user_groups (id, user_id, group_id)
                        SELECT id, user_id, group_id
                        FROM auth_user_groups
                        ON CONFLICT DO NOTHING;
                    END IF;
                END $$;

                DO $$
                BEGIN
                    IF to_regclass('public.auth_user_user_permissions') IS NOT NULL THEN
                        INSERT INTO accounts_user_user_permissions (id, user_id, permission_id)
                        SELECT id, user_id, permission_id
                        FROM auth_user_user_permissions
                        ON CONFLICT DO NOTHING;
                    END IF;
                END $$;

                SELECT setval(
                    pg_get_serial_sequence('accounts_user', 'id'),
                    COALESCE((SELECT MAX(id) FROM accounts_user), 1),
                    true
                );

                SELECT setval(
                    pg_get_serial_sequence('accounts_user_groups', 'id'),
                    COALESCE((SELECT MAX(id) FROM accounts_user_groups), 1),
                    true
                );

                SELECT setval(
                    pg_get_serial_sequence('accounts_user_user_permissions', 'id'),
                    COALESCE((SELECT MAX(id) FROM accounts_user_user_permissions), 1),
                    true
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
