name: Frontend CI

on:
  push:
    paths:
      - "apps/frontend/**"
      - ".github/workflows/frontend-ci.yml"

  pull_request:
    paths:
      - "apps/frontend/**"

permissions:
  id-token: write
  contents: read

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: apps/frontend
        run: |
          npm install

      # Step 4: Build Next.js
      - name: Build frontend
        working-directory: apps/frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000/api
        run: |
          npm run build

       # Step 5: Configure AWS credentials for image publishing
      - name: Configure AWS credentials
        #if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::385018113052:role/Digi2GitHubActionsECRPushRole
          aws-region: ca-central-1

      # Step 6: Login to Amazon ECR
      - name: Login to Amazon ECR
        #if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      # Step 7: Build and push frontend image
      - name: Build and push frontend image
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: digi2-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG apps/frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
